### This notebook is follows the Chapter 2 of Building LLMs from Scratch.

In [1]:
import os
import re
from typing import List

In [2]:
with open('the-verdict.txt', 'r') as f:
    raw_text = f.read()

# raw_text
print("Total number of character:", len(raw_text))
print(raw_text[:99])

Total number of character: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [3]:
#Now we are splitting the text.
#Also we are not normalizing or converting all text to small letters as this helps models learn the difference between proper noun and common noun
splitted_text = re.split(r'([.,\s])', raw_text)
print(splitted_text)
print(f"Total Tokens:{len(splitted_text)}")

['I', ' ', 'HAD', ' ', 'always', ' ', 'thought', ' ', 'Jack', ' ', 'Gisburn', ' ', 'rather', ' ', 'a', ' ', 'cheap', ' ', 'genius--though', ' ', 'a', ' ', 'good', ' ', 'fellow', ' ', 'enough--so', ' ', 'it', ' ', 'was', ' ', 'no', ' ', 'great', ' ', 'surprise', ' ', 'to', ' ', 'me', ' ', 'to', ' ', 'hear', ' ', 'that', ',', '', ' ', 'in', ' ', 'the', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory', ',', '', ' ', 'he', ' ', 'had', ' ', 'dropped', ' ', 'his', ' ', 'painting', ',', '', ' ', 'married', ' ', 'a', ' ', 'rich', ' ', 'widow', ',', '', ' ', 'and', ' ', 'established', ' ', 'himself', ' ', 'in', ' ', 'a', ' ', 'villa', ' ', 'on', ' ', 'the', ' ', 'Riviera', '.', '', ' ', '(Though', ' ', 'I', ' ', 'rather', ' ', 'thought', ' ', 'it', ' ', 'would', ' ', 'have', ' ', 'been', ' ', 'Rome', ' ', 'or', ' ', 'Florence', '.', ')', '\n', '', '\n', '"The', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory"--that', ' ', 'was', ' ', 'what', ' ', 'the', ' ', 'women', ' ', 'called', ' ', 'it

In [4]:
#Here we are removing the white spaces for learning and computational purposes but in reality one should keep them.
result = [item for item in splitted_text if item.strip()]
print(result)

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius--though', 'a', 'good', 'fellow', 'enough--so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"The', 'height', 'of', 'his', 'glory"--that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing--his', 'last', 'Chicago', 'sitter--deploring', 'his', 'unaccountable', 'abdication', '.', '"Of', 'course', "it's", 'going', 'to', 'send', 'the', 'value', 'of', 'my', 'picture', "'way", 'up;', 'but', 'I', "don't", 'think', 'of', 'that', ',', 'Mr', '.', 'Rickham--the', 'loss', 'to', 'Arrt', 'is', 'all', 'I', 'think', '

In [5]:
#Now we are expanding our token list for even special characters as well.
splitted_text = re.split(r'([.,;:?!()_%/\s"\']|--)', raw_text)
preprocessed = [item for item in splitted_text if item.strip()]

print(preprocessed)

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter', '--', 'deploring', 'his', 'unaccountable', 'abdication', '.', '"', 'Of', 'course', 'it', "'", 's', 'going', 'to', 'send', 'the', 'value', 'of', 'my', 'picture', "'", 'way', 'up', ';', 'but', 'I', 'don', "'", 't', 'think', 'of', 'that', ',

In [6]:
all_words = sorted(list(set(preprocessed)))
vocab_size = len(all_words)
print(vocab_size)

1130


In [7]:
vocab_dict = {token:token_id for token_id, token in enumerate(all_words)}

for i, item in enumerate(vocab_dict.items()):
    print(item)
    if i > 5:
        break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)


In [16]:
vocab_dict.items()

dict_items([('!', 0), ('"', 1), ("'", 2), ('(', 3), (')', 4), (',', 5), ('--', 6), ('.', 7), (':', 8), (';', 9), ('?', 10), ('A', 11), ('Ah', 12), ('Among', 13), ('And', 14), ('Are', 15), ('Arrt', 16), ('As', 17), ('At', 18), ('Be', 19), ('Begin', 20), ('Burlington', 21), ('But', 22), ('By', 23), ('Carlo', 24), ('Chicago', 25), ('Claude', 26), ('Come', 27), ('Croft', 28), ('Destroyed', 29), ('Devonshire', 30), ('Don', 31), ('Dubarry', 32), ('Emperors', 33), ('Florence', 34), ('For', 35), ('Gallery', 36), ('Gideon', 37), ('Gisburn', 38), ('Gisburns', 39), ('Grafton', 40), ('Greek', 41), ('Grindle', 42), ('Grindles', 43), ('HAD', 44), ('Had', 45), ('Hang', 46), ('Has', 47), ('He', 48), ('Her', 49), ('Hermia', 50), ('His', 51), ('How', 52), ('I', 53), ('If', 54), ('In', 55), ('It', 56), ('Jack', 57), ('Jove', 58), ('Just', 59), ('Lord', 60), ('Made', 61), ('Miss', 62), ('Money', 63), ('Monte', 64), ('Moon-dancers', 65), ('Mr', 66), ('Mrs', 67), ('My', 68), ('Never', 69), ('No', 70), ('Now

In [17]:
int_to_str = {i:s for s, i in vocab_dict.items()}

In [22]:
token_ids = [1, 58, 2, 872, 1013, 615, 541, 763, 5, 608, 5, 1, 69, 7, 3]
text = " ".join([int_to_str[token_id] for token_id in token_ids])
print(text)

" Jove ' sex tinge led hermit people , lay , " Never . (


In [27]:
text2 = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
print(text2)

" Jove' sex tinge led hermit people, lay," Never.(


In [ ]:
#Simple Implementation of a simple tokenizer class.Version 1
class SimpleTokenizerV1:

    def __init__(self, vocab):
        # pass
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}

    def encode(self, text):

        preprocessed = re.split(r'([.,;:?!()_%/\s"\']|--)', text)
        preprocessed = [item for item in preprocessed if item.strip()]
        ids = [self.str_to_int[token] for token in preprocessed]
        return ids
    def decode(self, ids:List):

        #join words/tokens with a s[ace]
        text = " ".join([self.int_to_str[token_id] for token_id in ids])

        #Here we are 
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)

        return text

In [34]:
#Tokenizing the text.
tokenizer = SimpleTokenizerV1(vocab_dict)
text = """It's the last he painted, you know," Mrs. Gisburn said"""
ids = tokenizer.encode(text)
print(ids)

[56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851]


In [35]:
#Lets see if we can decode the text.
recovered_text = tokenizer.decode(ids=ids)
print(recovered_text)

It' s the last he painted, you know," Mrs. Gisburn said


> Let's try with another text to see  what happens when a word is not in our vocabulary

In [ ]:
text = "Hello, do you like tea?"
tokenizer.encode(text)  #Since Hello was not in our vocab so it through an error.

KeyError: 'Hello'

> To address the issue of unknown words and end of text for separate doc we extend our vocab to incorporate two new tokens.

In [38]:
#Incorporating "<|endoftext|>", "<|unk|>"
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])
vocab_dict = {token:id for id, token in enumerate(all_tokens)}
print(f"New dict size:{len(all_tokens)}")

New dict size:1132


In [39]:
for i, item in enumerate(list(vocab_dict.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [43]:
vocab_dict['<|unk|>']

1131

In [ ]:
#Simple Tokenizer Version 2
class SimpleTokenizerV2:

    def __init__(self, vocab):
        # pass
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}

    def encode(self, text):

        preprocessed = re.split(r'([.,;:?!()_%/\s"\']|--)', text)
        preprocessed = [item for item in preprocessed if item.strip()]
        #modified from version 1 . 
        #Here we are replacing unknown words with id pf the <|unk|> token.
        ids = [self.str_to_int[token] if token in self.str_to_int.keys() else self.str_to_int["<|unk|>"] for token in preprocessed ]
        #The following also works.
        # preprocessed = [item if item in self.str_to_int else "<|unk|>" for item in preprocessed]
        # ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    def decode(self, ids:List):

        #join words/tokens with a s[ace]
        text = " ".join([self.int_to_str[token_id] for token_id in ids])

        #Here we are substituing the space followed by punctuation or special characters with only punctuation because Hi! Okay is right not Hi ! Okay.
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)

        return text

In [47]:
text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."
text = " <|endoftext|> ".join((text1, text2))
print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


In [50]:
#Checking the 2nd version of tokenizer.
tokenizer2 = SimpleTokenizerV2(vocab_dict)
ids2 = tokenizer2.encode(text)
print(ids2)

[1131, 5, 355, 1126, 628, 975, 10, 1130, 55, 988, 956, 984, 722, 988, 1131, 7]


In [ ]:
tokenizer2.decode(ids2) #Here we see both 'Hello' & 'palace' are mapped to unkown which could be problem for training models .

'<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.'

### There are also [BOS], [EOS], [PAD] tokens which are Beginning of Sequence and End of Sequnce and extra padding for batch fixed length training.

## 2.5 Byte-Pair Encoding

> This Encoding is used by top models.

> It can handle unkown words by breaking down words to its subword and even at character level when no matching subword is there.

> Tiktoken has been developed by OpenAI where they opensourced the encoding method for GPT-2 but only code not Dataset to create the vocab

In [3]:
import tiktoken

In [ ]:
print(tiktoken.list_encoding_names()) #Available tokenizers.

['gpt2', 'r50k_base', 'p50k_base', 'p50k_edit', 'cl100k_base', 'o200k_base', 'o200k_harmony']


In [4]:
tokenizer_gpt = tiktoken.get_encoding('gpt2')  #Here we are loading the tokenizer with the vocab of gpt-2
tokenizer_gpt.encode("Hello World!")

[15496, 2159, 0]

In [58]:
tokenizer_gpt.decode(tokenizer_gpt.encode("Hello World!"))

'Hello World!'

In [61]:
#gpt-2 uses allowed_special flag for encoding special tokens otherwise throws error.
text = "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
tokenizer_gpt.encode(text, allowed_special={'<|endoftext|>'})

[15496,
 11,
 466,
 345,
 588,
 8887,
 30,
 220,
 50256,
 554,
 262,
 4252,
 18250,
 8812,
 2114]

> Gpt-2 has a vocab size of 50257 with the '<|endoftext|>' being the last token

### 2.6 Data Sampling & SLiding Window Approach for Data Preparation for Next Token Prediction.

> The Idea is to creat a data to train using Self Supervised Style

> Given hello to predict How

> Given Hello How to predict are

> Given Hello How are to predict you?


In [5]:
with open('the-verdict.txt', 'r') as f:
    raw_text = f.read()

enc_text = tokenizer_gpt.encode(raw_text)
print(len(enc_text))  #Number of tokens as per gpt-2 tokenizer.

5145


In [6]:
#Sample data to work on.
enc_sample = enc_text[50:] #SInce first few tokens are special characters so for toy work taking after first 50.

In [ ]:
# It is common to train LLMs with input sizes of at least 256
context_size = 4 #Here we are taking the context/window size max at  4.

x = enc_sample[:context_size]
#target.
y = enc_sample[1:context_size+1]
print(f'x:{x}')
print(f'y:  {y}') #target is input shifted by 1.

x:[290, 4920, 2241, 287]
y:  [4920, 2241, 287, 257]


In [8]:
#So thetraining task and the dataset should look like this.
for i in range(1, context_size+1):

    context = enc_sample[:i]
    target = enc_sample[i]

    print(f"Input:{context} --> Target:{target}")

Input:[290] --> Target:4920
Input:[290, 4920] --> Target:2241
Input:[290, 4920, 2241] --> Target:287
Input:[290, 4920, 2241, 287] --> Target:257


In [9]:
#So thetraining task and the dataset should look like this.
for i in range(1, context_size+1):

    context = enc_sample[:i]
    target = enc_sample[i]

    print(f"Input:{tokenizer_gpt.decode(context)} --> Target:{tokenizer_gpt.decode([target])}")

Input: and --> Target: established
Input: and established --> Target: himself
Input: and established himself --> Target: in
Input: and established himself in --> Target: a


> Now to implement this type of Training Dataset Preparation we will use highly efficient Pytorch Dataset & DataLoaders.

> Image of how the dataset is prepared as.

![Alt Text](pics/LLM_Dataset_Preparation.png)

> Dataset Stride related image:

![Alt Text](pics/LLM_Stride.png)

In [10]:
import torch
from torch.utils.data import Dataset, DataLoader

In [ ]:
class GPTDataset_V1(Dataset):
    #For a class that inherits from abstract class o Dataset we need to incorporate __init_(), __len__() & __getitem__() methods.
    def __init__(self, text_corpus, tokenizer, max_length, stride=1):
        self.tokenizer = tokenizer
        self.input_ids = []
        self.target_ids = []

        token_ids = self.tokenizer.encode(text_corpus)

        #Creating the dataset.
        for i in range(0, len(token_ids) - max_length, stride):  #Here we will by default use 1 stride for our text corpus.
            input_chunk = token_ids[i:i+max_length]
            target_chunk = token_ids[i+1:i+max_length+1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return  len(self.input_ids)

    def __getitem__(self, idx):
        return  self.input_ids[idx], self.target_ids[idx]

In [14]:
#Checking the dataset only.
text_dataset = GPTDataset_V1(text_corpus=raw_text, tokenizer=tokenizer_gpt, max_length=4, stride=1)
#Fetching a particular input-target pair.
text_dataset.__getitem__(idx=5) #We can also do text_dataset[5] same thing.

(tensor([ 3619,   402,   271, 10899]), tensor([  402,   271, 10899,  2138]))

In [45]:
#> For multiple indices fetching in Dataset.
text_dataset[1:3]

([tensor([ 367, 2885, 1464, 1807]), tensor([2885, 1464, 1807, 3619])],
 [tensor([2885, 1464, 1807, 3619]), tensor([1464, 1807, 3619,  402])])

In [46]:
#Now we implement the DataLoader class.
def create_dataloader_v1(text, max_length, stride, batch_size, shuffle):

    gpt_tokenizer = tiktoken.get_encoding('gpt2')
    dataset = GPTDataset_V1(text_corpus=text, tokenizer=gpt_tokenizer, max_length=max_length, stride=stride)
    dataloader = DataLoader(dataset=dataset, batch_size=batch_size, shuffle=shuffle, drop_last=True)

    return dataloader

In [ ]:
with open('the-verdict.txt', 'r') as f:
    raw_text = f.read()
#Using the DataLoader .    
text_dataloader_stride1 = create_dataloader_v1(text=raw_text, max_length=4, stride=1, batch_size=4, shuffle=False) #Shuffling shuffles the batches.
data_iter = iter(text_dataloader_stride1)
first_batch_input, first_batch_target = next(data_iter)
print(f'Stride 1 result\nFirst Batch Input (x):\n\n{first_batch_input}\n\nFirst Batch Target(y):\n{first_batch_target} & \nBatch Size:{len(first_batch_input)}\nBatch Shape:{first_batch_input.shape}')

Stride 1 result
First Batch Input (x):

tensor([[  40,  367, 2885, 1464],
        [ 367, 2885, 1464, 1807],
        [2885, 1464, 1807, 3619],
        [1464, 1807, 3619,  402]])

First Batch Target(y):
tensor([[ 367, 2885, 1464, 1807],
        [2885, 1464, 1807, 3619],
        [1464, 1807, 3619,  402],
        [1807, 3619,  402,  271]]) & 
Batch Size:4
Batch Shape:torch.Size([4, 4])


In [52]:
#Stride = 4 avoids any overlap between batch as it is the context size .
# If stride = max_length or context_size then no overlap between batches.
with open('the-verdict.txt', 'r') as f:
    raw_text = f.read()
#Using the DataLoader .    
text_dataloader_stride4 = create_dataloader_v1(text=raw_text, max_length=4, stride=4, batch_size=4, shuffle=False) #Shuffling shuffles the batches.
data_iter = iter(text_dataloader_stride4)
first_batch_input, first_batch_target = next(data_iter)
print(f'Stride 4 result\nFirst Batch Input (x):\n\n{first_batch_input}\n\nFirst Batch Target(y):\n{first_batch_target} & \nBatch Size:{len(first_batch_input)}\nBatch Shape:{first_batch_input.shape}')

Stride 4 result
First Batch Input (x):

tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257]])

First Batch Target(y):
tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922]]) & 
Batch Size:4
Batch Shape:torch.Size([4, 4])


In [48]:
first_batch_input.size()

torch.Size([4, 4])

### 2.7 Creating token embeddings (Last Step before Training Architecture)

![Alt Text](pics/Token_Embedding.png)

> Token Embedding Look up Image

![Alt Text](pics/Token_Embed_Lookup.png)

In [53]:
#Say for our Learning purposes we only have a 4 token input.
input_ids = torch.tensor([2, 3, 5, 1])

#Suppose we have vocab size of 10 and output dim is 4 (In Reality the Output dim for gpt2 is 783)
vocab_size, output_dim = 10, 4
#Initializing a Random EMbedding / Matrix for our Vocabulary set.
#num_embeddings -> Vocabulary Size, embedding_dim  -> Output Dimension.
embedding = torch.nn.Embedding(num_embeddings=vocab_size, embedding_dim=output_dim)

In [56]:
#Now to access a token embedding of the token_id = 3
embedding(torch.tensor([3]))  #We can also do embedding.weight[3] 
#Why call a vector weight because even if it is a vector we learn the rich contextual vector/embedding representation so we call it parameter /weight.

tensor([[0.7412, 0.4882, 0.8316, 1.1347]], grad_fn=<EmbeddingBackward0>)

In [58]:
#Setting seed.
torch.manual_seed(42)
embedding = torch.nn.Embedding(num_embeddings=vocab_size, embedding_dim=output_dim)
print(embedding.weight)

Parameter containing:
tensor([[ 1.9269,  1.4873,  0.9007, -2.1055],
        [ 0.6784, -1.2345, -0.0431, -1.6047],
        [-0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624],
        [ 1.6423, -0.1596, -0.4974,  0.4396],
        [-0.7581,  1.0783,  0.8008,  1.6806],
        [ 0.0349,  0.3211,  1.5736, -0.8455],
        [ 1.3123,  0.6872, -1.0892, -0.3553],
        [-1.4181,  0.8963,  0.0499,  2.2667],
        [ 1.1790, -0.4345, -1.3864, -1.2862]], requires_grad=True)


In [62]:
#Fetching all the token embeddings of the input_ids which is 3 x 4 matrix
input_ids = torch.tensor([2, 3, 5])
embedding(input_ids)

tensor([[-0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624],
        [-0.7581,  1.0783,  0.8008,  1.6806]], grad_fn=<EmbeddingBackward0>)

### 2.8 Encoding word positions

> There are 2 types of Postional Embeddings: 1. Absolute Positional Embeddings 2. Relative Positional Embeddings.

> In Early Gpt Models OpenAI used Absoulte Positional Embeddings but they were also trained and updated and optimized during training mechanism.

> Absolute Positional Embeddings Image.

![Alt Text](pics/Absolute_Positional_Embedding.png)

In [66]:
#Implemeting Positional Embeddings.
#Let's Imagine we have Vocab size of 50257 and output_dim of 256.
output_dim, vocab_size = 256, 50257
#So our token embedding for our entire vocabulary is:
token_embedding_layer = torch.nn.Embedding(num_embeddings=vocab_size, embedding_dim=output_dim)

#Now we need to create Absolute Positional Embeddings for our tokensbut with same output dim.
max_length = 4
dataloader = create_dataloader_v1(text=raw_text, max_length=max_length, stride=max_length, batch_size=8, shuffle=True)

data_iter = iter(dataloader)
batch_inputs, batch_targets = next(data_iter)
print("Token IDs:\n", batch_inputs)
print("\nInputs shape:\n", batch_inputs.shape)


Token IDs:
 tensor([[   11,   508,   550, 18459],
        [30960,   198,   198,     1],
        [  326,  9074,    13,   402],
        [ 1049,  5975,   284,   502],
        [ 1890,   262,   717,   640],
        [  523,   618,   673,  2540],
        [  373,   366, 47914,  1298],
        [  314,  3114,   510,    11]])

Inputs shape:
 torch.Size([8, 4])


> Now the data is 8 x 4 size that is a batch of 8 inputs with context window of 4.

> Now we need to get the initialized embeddings for this 1 batch oonly which should be 8 x 4 x 256 as the embedding/output dim is 256.

In [ ]:
#Token Embedding.
token_embeddings = token_embedding_layer(batch_inputs)  #Getting the Embedding of the batch input tokens of size 8 x 4
print("One batch embedding shape:",token_embeddings.shape)

One batch embedding shape: torch.Size([8, 4, 256])


> Absolute Positional Embedding Creation

In [71]:
#Positional EMbedding.
context_length = max_length
postional_embedding_layer = torch.nn.Embedding(num_embeddings=context_length, embedding_dim=output_dim)

#This code : torch.arange(4) produces: tensor([0, 1, 2, 3]) which we need to get postional embedding vector intialization
positional_embeddings = postional_embedding_layer(torch.arange(context_length))
print('Positional Embedding Shape:',positional_embeddings.shape)

Positional Embedding Shape: torch.Size([4, 256])


In [ ]:
#Input Embedding.
#Now we need to do token embedding vector + postional embedding vector -> Input Embedding.
input_embeddings= token_embeddings + positional_embeddings
print('Input Embedding shape',input_embeddings.shape)

Input Embedding shape torch.Size([8, 4, 256])


In [69]:
torch.arange(4)

tensor([0, 1, 2, 3])

![Alt Text](pics/Transformer_Decoder.png)